### ISSUE TITLE
internal server error when username clash

### ISSUE THREAD

**Issue by individual-it** [owncloud/user_external#7]
1. create a user in oC that has the same name as the FTP user
1. try to login as this user

```
{"reqId":"1wFkaX73AHHDeRMN5RHE","level":2,"time":"2019-04-29T09:13:09+00:00","remoteAddr":"127.0.0.1","user":"--","app":"OC\\User\\SyncService","method":"POST","url":"\/owncloud-10.2.0\/rc1_c\/index.php\/login","message":"User <bob> already provided by another backend(OC\\User\\Database !== OC_User_FTP), skipping."}
{"reqId":"1wFkaX73AHHDeRMN5RHE","level":3,"time":"2019-04-29T09:13:09+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"POST","url":"\/owncloud-10.2.0\/rc1_c\/index.php\/login","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Returned account has different backend to the requested backend for sync\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/User\\\/Manager.php(254): OC\\\\User\\\\SyncService->createOrSyncAccount('bob', Object(OC_User_FTP))\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/User\\\/Session.php(520): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/User\\\/Session.php(333): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/core\\\/Controller\\\/LoginController.php(203): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/login')\\n#10 \\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-10.2.0\\\/rc1_c\\\/lib\\\/private\\\/User\\\/SyncService.php\",\"Line\":372}"}
```

no login possible

**Comment by tomneedham** [comment]
Expectation? Maybe configurable to aloow login and 'merge' accounts? Usually we die by default, to avoid exposing the wrong users data.
